-- Script de criação das tabelas no Oracle 23c

-- Tabela: T_ANO_AGRICOLA
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_ANO_AGRICOLA (
        IDT_ANO_AGRICOLA NUMBER PRIMARY KEY,
        TXT_ANO_AGRICOLA VARCHAR2(10)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_ANO_AGRICOLA já existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Tabela: T_SAFRA
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_SAFRA (
        IDT_SAFRA NUMBER PRIMARY KEY,
        DES_SAFRA VARCHAR2(50)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_SAFRA já existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Tabela: T_UF
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_UF (
        IDT_UF NUMBER PRIMARY KEY,
        SIG_UF VARCHAR2(2)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_UF já existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Tabela: T_PRODUTO
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_PRODUTO (
        IDT_PRODUTO NUMBER PRIMARY KEY,
        NOM_PRODUTO VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_PRODUTO já existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Tabela: T_LEVANTAMENTO
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_LEVANTAMENTO (
        IDT_LEVANTAMENTO NUMBER PRIMARY KEY,
        DES_LEVANTAMENTO VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_LEVANTAMENTO já existe.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Tabela: T_PRODUCAO
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_PRODUCAO (
        IDT_PRODUCAO NUMBER PRIMARY KEY,
        QTD_AREA_PLANTADA_MIL_HA NUMBER,
        QTD_PRODUCAO_MIL_T NUMBER,
        QTD_PRODUTIVIDADE_MIL_HA_MIL_T NUMBER,
        IDT_ANO_AGRICOLA NUMBER REFERENCES T_ANO_AGRICOLA(IDT_ANO_AGRICOLA),
        IDT_SAFRA NUMBER REFERENCES T_SAFRA(IDT_SAFRA),
        IDT_UF NUMBER REFERENCES T_UF(IDT_UF),
        IDT_PRODUTO NUMBER REFERENCES T_PRODUTO(IDT_PRODUTO),
        IDT_LEVANTAMENTO NUMBER REFERENCES T_LEVANTAMENTO(IDT_LEVANTAMENTO)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_PRODUCAO já existe.');
        ELSE
            RAISE;
        END IF;
END;
/
