-- Agora, faça login como usrfiap para criar as tabelas no schema dedicado.
-- Use o script a seguir após logar como usrfiap.

-- Criação do banco de dados e tabelas no schema usrfiap

-- Criação da tabela T_PRODUTO
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_PRODUTO (
        "idt_produto" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "nom_produto" VARCHAR2(100) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_PRODUTO já existe. Não será criada novamente.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Criação da tabela T_SAFRA
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_SAFRA (
        "idt_safra" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "dat_ano" NUMBER(4) NOT NULL,
        "dat_safra_inicial" NUMBER(4),
        "dat_safra_final" NUMBER(4)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_SAFRA já existe. Não será criada novamente.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Criação da tabela T_PRODUCAO_ANUAL
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_PRODUCAO_ANUAL (
        "idt_producao_anual" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "idt_produto" NUMBER REFERENCES T_PRODUTO("idt_produto"),
        "idt_safra" NUMBER REFERENCES T_SAFRA("idt_safra"),
        "qtd_area_plantada" NUMBER(15, 2) NOT NULL,
        "qtd_producao" NUMBER(15, 2) NOT NULL,
        "val_produtividade" NUMBER(10, 2),
        "des_visao" VARCHAR2(50),
        "nom_regiao" VARCHAR2(100),
        "sig_uf" CHAR(2)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_PRODUCAO_ANUAL já existe. Não será criada novamente.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Criação da tabela T_PRODUCAO_HISTORICA
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_PRODUCAO_HISTORICA (
        "idt_producao_historica" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "idt_produto" NUMBER REFERENCES T_PRODUTO("idt_produto"),
        "idt_safra" NUMBER REFERENCES T_SAFRA("idt_safra"),
        "qtd_area_plantada" NUMBER(15, 2) NOT NULL,
        "qtd_producao" NUMBER(15, 2) NOT NULL,
        "val_produtividade" NUMBER(10, 2),
        "des_visao" VARCHAR2(50),
        "nom_regiao" VARCHAR2(100),
        "sig_uf" CHAR(2)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Tabela T_PRODUCAO_HISTORICA já existe. Não será criada novamente.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Listar todas as tabelas e colunas criadas para verificação
BEGIN
    DBMS_OUTPUT.PUT_LINE('Listagem de tabelas e colunas criadas:');
    
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('T_PRODUTO', 'T_SAFRA', 'T_PRODUCAO_ANUAL', 'T_PRODUCAO_HISTORICA'))
    LOOP
        DBMS_OUTPUT.PUT_LINE('Tabela: ' || t.table_name);
        
        FOR c IN (SELECT column_name, data_type FROM user_tab_columns WHERE table_name = t.table_name)
        LOOP
            DBMS_OUTPUT.PUT_LINE('  - Coluna: ' || c.column_name || ' | Tipo de dado: ' || c.data_type);
        END LOOP;
    END LOOP;
END;
/
